# Generated by Django 6.0.7 on 2026-08-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_name', models.CharField(max_length=100, unique=True)),
                ('leave_code', models.CharField(max_length=10, unique=True)),
                ('maximum_days', models.PositiveIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=True)),
                ('color', models.CharField(default='#0d6efd', help_text='Hex color code', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'ordering': ['leave_name'],
            },
        ),
    ]
