# Generated by Django 6.0.7 on 2026-08-01 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='section',
            name='academic_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.academiclevel'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('academic_level', 'name')},
        ),
    ]
