# Generated by Django 6.0.7 on 2026-08-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_section_options_alter_section_academic_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academiclevel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['academic_level', 'name']},
        ),
    ]
