# Generated by Django 6.0.7 on 2026-08-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_academiclevel_options_alter_section_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.RemoveField(
            model_name='section',
            name='academic_level',
        ),
    ]
