# Generated by Django 6.0.7 on 2026-08-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_admission_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
