# Generated by Django 6.0.7 on 2026-09-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrequest',
            options={'ordering': ['-created_at']},
        ),
    ]
