# Generated by Django 6.0.7 on 2026-09-28 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_alter_section_options_alter_section_unique_together_and_more'),
        ('teachers', '0002_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('assigned_date', models.DateField()),
                ('due_date', models.DateField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homework/attachments/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_assignments', to='academics.academiclevel')),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_assignments', to='academics.academicsession')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_assignments', to='academics.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_assignments', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-assigned_date', '-created_at'],
                'indexes': [models.Index(fields=['academic_session', 'academic_level', 'section'], name='homework_ho_academi_7653bf_idx'), models.Index(fields=['due_date'], name='homework_ho_due_dat_12e964_idx'), models.Index(fields=['is_published'], name='homework_ho_is_publ_3ac09d_idx')],
            },
        ),
    ]
