# Generated by Django 6.0.7 on 2026-08-14 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_section_options_alter_section_unique_together_and_more'),
        ('attendance', '0002_attendance_academic_level_and_more'),
        ('students', '0007_alter_student_admission_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'attendance_date'), name='unique_student_attendance_date'),
        ),
    ]
